name: client_type_safe_route_test
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  # 상태관리
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # 네트워크
  http: ^1.2.2
  dio: ^5.7.0
  retrofit: ^4.4.1
  retrofit_generator: ^9.1.4
  logger: ^2.5.0

  # 데이터 모델링 및 직렬화
  freezed: ^2.5.7
  collection: ^1.18.0
  json_annotation: ^4.9.0
  intl: ^0.19.0

  get_it: ^8.0.3
  injectable: ^2.5.0
  injectable_generator: ^2.6.2
  freezed_annotation: ^2.4.4
  go_router: ^14.6.2
  go_router_builder: ^2.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.0
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.3
  riverpod_generator: ^2.6.3

flutter:
  uses-material-design: true
